nacionalidades = {
	"Argentina":"Argentina",
	"Boliviana":"Bolivia",
	"Brasileña":"Brasil",
	"Chilena":"Chile",
	"Colombiana":"Colombia",
	"Ecuatoriana":"Ecuador",
	"Haitiana":"Haití",
	"Mexicana":"México",
	"Peruana":"Perú",
	"Venezolana":"Venezuela",
	"Afgana":"Afganistán",
	"Albana":"Albania",
	"Alemana":"Alemania",
	"Andorra":"Andorra",
	"Angola":"Angola",
	"Arabe":"Arabia Saudita",
	"Argelina":"Argelia",
	"Armenia":"Armenia",
	"Aruba":"Aruba",
	"Australiana":"Australia",
	"Austriaca":"Austria",
	"Bahamas":"Bahamas",
	"Bahrein":"Bahrein",
	"Bangladesh":"Bangladesh",
	"Barbados":"Barbados",
	"Belarús":"Belarús",
	"Bélgica":"Bélgica",
	"Belice":"Belice",
	"Benín":"Benín",
	"Bermuda, Isla":"Bermuda, Isla",
	"Bhután":"Bhután",
	"Myanmar (Birmania)":"Birmania",
	"Bosnia & hrzegovina":"Bosnia y Herzegovina",
	"Botswana":"Botswana",
	"Brunei Darussalam":"Brunei Darussalam",
	"Bulgara":"Bulgaria",
	"Burkina Faso":"Burkina Faso",
	"Burundi":"Burundi",
	"Cabo Verde":"Cabo Verde",
	"Camboya":"Camboya",
	"Camerún":"Camerún",
	"Canadá":"Canadá",
	"Chad":"Chad",
	"China":"China",
	"Chipre":"Chipre",
	"Comoras":"Comoras",
	"Congo":"Congo",
	"Corea del Norte":"Corea del Norte",
	"Corea del Sur":"Corea del Sur",
	"Costa Rica":"Costa Rica",
	"Croacia":"Croacia",
	"Cuba":"Cuba",
	"Dinamarca":"Dinamarca",
	"Djibouti":"Djibouti",
	"Dominica":"Dominica",
	"Egipto":"Egipto",
	"El Salvador":"El Salvador",
	"Emiratos Arabes Unid":"Emiratos Árabes Unidos",
	"Eritrea":"Eritrea",
	"Eslovaca":"Eslovaquia",
	"Eslovenia":"Eslovenia",
	"Española":"España",
	"Estados Unidos":"Estados Unidos",
	"Estonia":"Estonia",
	"Etiopia":"Etiopia",
	"Filipina":"Filipinas",
	"Finladesa":"Finlandia",
	"Fiji":"Fiyi",
	"Francesa":"Francia",
	"Gabón":"Gabón",
	"Gambia":"Gambia",
	"Georgia":"Georgia",
	"Ghana":"Ghana",
	"Gilbrartar":"Gibraltar",
	"Grenada":"Granada",
	"Grecia":"Grecia",
	"Groenlandia":"Groenlandia",
	"Guadalupe":"Guadalupe",
	"Guam":"Guam",
	"Guatemala":"Guatemala",
	"Guayana Francesa":"Guayana Francesa",
	"Guinea":"Guinea",
	"Guinea Ecuatorial":"Guinea Ecuatorial",
	"Guinea-Bissau":"Guinea-Bissau",
	"Guyana":"Guyana",
	"Holandés":"Holanda (Paieses Bajos)",
	"Honduras":"Honduras",
	"Hong Kong":"Hong Kong",
	"Hungria":"Hungría",
	"India":"India",
	"Indonesia":"Indonesia",
	"Oiraq":"Irak",
	"Iraní":"Irán",
	"Irlanda":"Irlanda",
	"Norfolk, Islas":"Isla Norfolk",
	"Islandia":"Islandia",
	"Feroe, Islas":"Islas Feroe",
	"Marshall, Islas":"Islas Marshall",
	"Israel":"Israel",
	"Italia":"Italia",
	"Jamaica":"Jamaica",
	"Japón":"Japón",
	"Jordania":"Jordania",
	"Kazajstán":"Kazajistán",
	"Kenya":"Kenia",
	"Kirguistán":"Kirguistán",
	"Kiribati":"Kiribati",
	"Kuwait":"Kuwait",
	"Laos, Rep. Dem. Pop.":"Laos",
	"Lesotho":"Lesoto",
	"Letonia (Latvia)":"Letonia",
	"Libano":"Líbano",
	"Liberia":"Liberia",
	"Libia, Ja Libia":"Libia",
	"Liechtenstein":"Liechtenstein",
	"Lituania":"Lituania",
	"Luxemburgo":"Luxemburgo",
	"Macao":"Macao",
	"Macedonia, The Former Yugosl":"Macedonia del Norte",
	"Madagascar":"Madagascar",
	"Malasia":"Malasia",
	"Malawi":"Malawi",
	"Maldivas":"Maldivas",
	"Mali":"Malí",
	"Malta":"Malta",
	"Marianas del Norte,":"Marianas del Norte",
	"Marruecos":"Marruecos",
	"Martinica":"Martinica",
	"Mauricio":"Mauricio",
	"Mauritania":"Mauritania",
	"Mayotte":"Mayotte",
	"Micronesia":"Micronesia",
	"Moldova, República de":"Moldavia",
	"Mónaco":"Mónaco",
	"Mongolia":"Mongolia",
	"Montserrat":"Montserrat",
	"Mozambique":"Mozambique",
	"Namibia":"Namibia",
	"Nauru":"Nauru",
	"Nepal":"Nepal",
	"Nicaragua":"Nicaragua",
	"Niger":"Níger",
	"Nigeria":"Nigeria",
	"Niue":"Niue",
	"Noruega":"Noruega",
	"Nueva Caledonia":"Nueva Caledonia",
	"Nueva Zelandia":"Nueva Zelanda",
	"Omán":"Omán",
	"Pakistán":"Pakistán",
	"Palau":"Palaos",
	"Panamá":"Panamá",
	"Papua Nueva Guinea":"Papúa Nueva Guinea",
	"Paraguay":"Paraguay",
	"Polonia":"Polonia",
	"Portugal":"Portugal",
	"Puerto Rico":"Puerto Rico",
	"Qatar":"Qatar",
	"Reino Unido":"Reino Unido",
	"República Centroafri":"República Centroafricana",
	"República Checa":"República Checa",
	"República Dominicana":"República Dominicana",
	"Reunión":"Reunión",
	"Ruanda":"Ruanda",
	"Rumania":"Rumania",
	"Rusia":"Rusia",
	"Samoa":"Samoa",
	"Samoa Americana":"Samoa Americana",
	"Senegal":"Senegal",
	"Seychelles":"Seychelles",
	"Sierra Leona":"Sierra Leona",
	"Singapur":"Singapur",
	"Siria, República Ara":"Siria",
	"Somalia":"Somalia",
	"Sri Lanca":"Sri Lanka",
	"Sudafrica":"Suazilandia",
	"Sudán":"Sudáfrica",
	"Suecia":"Sudán",
	"Suiza":"Suecia",
	"Suriname":"Suiza",
	"Swazilandia":"Surinam",
	"Tailandia":"Tailandia",
	"Taiwan, Provincia de":"Taiwan, Provincia de",
	"Tanzania":"Tanzania",
	"Tayikistán":"Tayikistán",
	"Timor Oriental":"Timor Oriental",
	"Togo":"Togo",
	"Tokelau":"Tokelau",
	"Tonga":"Tonga",
	"Trinidad y Tobago":"Trinidad y Tobago",
	"Túnez":"Túnez",
	"Turkmenistán":"Turkmenistán",
	"Turquia":"Turquía",
	"Tuvalu":"Tuvalu",
	"Ucrania":"Ucrania",
	"Uganda":"Uganda",
	"Uruguay":"Uruguay",
	"Uzbekistán":"Uzbekistán",
	"Vanuatu":"Vanuatu",
	"Vaticano":"Vaticano",
	"Viet Nam":"Vietnam",
	"Yemen":"Yemen",
	"Yugoslavia":"Yugoslavia",
	"Zaire":"Zaire",
	"Zambia":"Zambia",
	"Zimbabwe":"Zimbabwe",
}

paises = [
	"Argentina",
	"Bolivia",
	"Brasil",
	"Chile",
	"Colombia",
	"Ecuador",
	"Haití",
	"México",
	"Perú",
	"Venezuela",
	"Afganistán",
	"Albania",
	"Alemania",
	"Andorra",
	"Angola",
	"Arabia Saudita",
	"Argelia",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Bahamas",
	"Bahrein",
	"Bangladesh",
	"Barbados",
	"Belarús",
	"Bélgica",
	"Belice",
	"Benín",
	"Bermuda, Isla",
	"Bhután",
	"Birmania",
	"Bosnia y Herzegovina",
	"Botswana",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Camboya",
	"Camerún",
	"Canadá",
	"Chad",
	"China",
	"Chipre",
	"Comoras",
	"Congo",
	"Corea del Norte",
	"Corea del Sur",
	"Costa Rica",
	"Croacia",
	"Cuba",
	"Dinamarca",
	"Djibouti",
	"Dominica",
	"Egipto",
	"El Salvador",
	"Emiratos Árabes Unidos",
	"Eritrea",
	"Eslovaquia",
	"Eslovenia",
	"España",
	"Estados Unidos",
	"Estonia",
	"Etiopia",
	"Filipinas",
	"Finlandia",
	"Fiyi",
	"Francia",
	"Gabón",
	"Gambia",
	"Georgia",
	"Ghana",
	"Gibraltar",
	"Granada",
	"Grecia",
	"Groenlandia",
	"Guadalupe",
	"Guam",
	"Guatemala",
	"Guayana Francesa",
	"Guinea",
	"Guinea Ecuatorial",
	"Guinea-Bissau",
	"Guyana",
	"Holanda (Paieses Bajos)",
	"Honduras",
	"Hong Kong",
	"Hungría",
	"India",
	"Indonesia",
	"Irak",
	"Irán",
	"Irlanda",
	"Isla Norfolk",
	"Islandia",
	"Islas Feroe",
	"Islas Marshall",
	"Israel",
	"Italia",
	"Jamaica",
	"Japón",
	"Jordania",
	"Kazajistán",
	"Kenia",
	"Kirguistán",
	"Kiribati",
	"Kuwait",
	"Laos",
	"Lesoto",
	"Letonia",
	"Líbano",
	"Liberia",
	"Libia",
	"Liechtenstein",
	"Lituania",
	"Luxemburgo",
	"Macao",
	"Macedonia del Norte",
	"Madagascar",
	"Malasia",
	"Malawi",
	"Maldivas",
	"Malí",
	"Malta",
	"Marianas del Norte",
	"Marruecos",
	"Martinica",
	"Mauricio",
	"Mauritania",
	"Mayotte",
	"Micronesia",
	"Moldavia",
	"Mónaco",
	"Mongolia",
	"Montserrat",
	"Mozambique",
	"Namibia",
	"Nauru",
	"Nepal",
	"Nicaragua",
	"Níger",
	"Nigeria",
	"Niue",
	"Noruega",
	"Nueva Caledonia",
	"Nueva Zelanda",
	"Omán",
	"Pakistán",
	"Palaos",
	"Panamá",
	"Papúa Nueva Guinea",
	"Paraguay",
	"Polonia",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Reino Unido",
	"República Centroafricana",
	"República Checa",
	"República Dominicana",
	"Reunión",
	"Ruanda",
	"Rumania",
	"Rusia",
	"Samoa",
	"Samoa Americana",
	"Senegal",
	"Seychelles",
	"Sierra Leona",
	"Singapur",
	"Siria",
	"Somalia",
	"Sri Lanka",
	"Suazilandia",
	"Sudáfrica",
	"Sudán",
	"Suecia",
	"Suiza",
	"Surinam",
	"Tailandia",
	"Taiwan, Provincia de",
	"Tanzania",
	"Tayikistán",
	"Timor Oriental",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad y Tobago",
	"Túnez",
	"Turkmenistán",
	"Turquía",
	"Tuvalu",
	"Ucrania",
	"Uganda",
	"Uruguay",
	"Uzbekistán",
	"Vanuatu",
	"Vaticano",
	"Vietnam",
	"Yemen",
	"Yugoslavia",
	"Zaire",
	"Zambia",
	"Zimbabwe",
]


# with open("output.py", 'w', encoding="utf-8") as file:
#     file.write("nacionalidades = {\n")
#     for key, value in nacionalidad.items():
#         file.write(f"\t\"{value}\":\"{key}\",\n")
#     file.write("}\n\n")
#     file.write("paises = [\n")
#     for key, value in nacionalidad.items():
#         file.write(f"\t\"{key}\",\n")
#     file.write("]")